### ISSUE TITLE
setup.py wrong version

### ISSUE THREAD

**Issue by pocin** [keboola/python-docker-application#4]
`setup.py` script contains version `0.1.0` while the actual version is different (afaik). I think this could make problems when upgrading `pip install --upgrade ...`.

A slight improvement might be writing  into `keboola/__init__.py`

```
__version__ = '0.1.0' # or the actual version according to latest stable git tag
```

in setup.py
```
import keboola
setup(
...,
version=keboola.__version__,
)
```

It still requires manual updating of the __version__ variable, but is more elegant imo :)

**Comment by pocin** [comment]
On a second thought It probably isn't such a big issue, since this package is installed in clean containers and is rarely upgraded (if ever). But I noticed it and pointed it out, just in case.

**Comment by odinuv** [comment]
yes, It is an issue only if you install the library locally, in production a specific git tag is always referenced https://github.com/keboola/docker-custom-python/blob/master/Dockerfile#L35 and installed in clean container.

I had a look on possible solutions and I can't any which is not absurdly complex. I have updated readme with a more correct update command. Given how rarely this lib updates - I'd close this as won't fix.
